version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 16-bullseye
    volumes:
      - ..:/workspace
    command: sleep infinity
    networks:
      - backend

  db:
    container_name: db
    restart: unless-stopped
    image: mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

  jsonbox:
    container_name: jsonbox
    restart: always
    environment:
      - MONGODB_URI=mongodb://db:27017/jsonbox-io-dev
    image: harlev/jsonbox
    networks:
      - backend
    depends_on:
      - db

volumes:
  mongo_data:

networks:
  backend:
    driver: bridge
