version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 16-bullseye
    volumes:
      - ..:/workspace
    command: sleep infinity
    networks:
      - frontend

  db:
    restart: unless-stopped
    image: mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

  backend:
    restart: unless-stopped
    environment:
      - MONGODB_URI=mongodb://db:27017/item
    image: caserage/inventory-management-server:beta
    ports:
      - 3001:3000
    networks:
      - frontend
      - backend
    depends_on:
      - db

volumes:
  mongo_data:

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
